---
title: "Parks Canada - Intermediate R"
format: html
---

This website contains the materials for the Parks Canada Intermediate R workshop. The workshop is designed to help participants improve their R programming skills, focusing on efficient workflows, , and reproducible research practices.

## Workshop Overview:

This intermediate R workshop is designed for data professionals and scientists who have basic R experience and want to advance their skills in data analysis and programming.

This will be an online, interactive workshop delivered virtually.

## Modules

### 1. [Project-oriented workflows and effective use of your IDE (RStudio/Positron)](workflows.qmd)

### 2. [Version control and Collaboration with Git and GitHub](git-github.qmd)

### 3. [Advanced data manipulation with dplyr and tidyr](data-manipulation.qmd)

### 4. [Programming with R - functions](programming-functions.qmd)

### 5. [String manipulation and regular expressions with stringr](regex.qmd)

### 6. [Iteration and functional programming with purrr](programming-iteration.qmd)

### 7. [Reproducible reporting with Quarto](quarto.qmd)

## Exercises

- Exercises (with solutions) for the data manipulation module can be found [here](https://github.com/ateucher/pc-data-manipulation).
- Exercises (with solutions) for the programming module can be found [here](https://github.com/ateucher/pc-programming).

## Prework

Please ensure you have completed the steps in [System Setup](setup.qmd).

## Instructor:

[***Andy Teucher***](https://andyteucher.ca) is a freelance data scientist and package developer with a passion for teaching others how to use data science tools to make their work more efficient and reproducible. His background is in conservation biology, with an MSc in Ecology from the University of Calgary. He has spent much of his career as a data scientist in government, where he made it his mission to promote and teach open, reproducible data science practices. He has written many R packages for internal use in his teams as well as for a broader audience, with several hosted on CRAN. Andy is a certified Software Carpentry and Data Carpentry instructor, and has led many workshops teaching programming skills to scientists and data professionals.

## Acknowledgements and Resources:

The material for this workshop has origins and inspiration from several sources, including:

- [Happy Git and GitHub for the useR](https://happygitwithr.com/): A free book by Jenny Bryan and Jim Hester that teaches version control with Git and GitHub using R.

- [The Carpentries](https://carpentries.org/): An organization dedicated to teaching foundational coding and data science skills to researchers worldwide.

- [R for Data Science](https://r4ds.had.co.nz/): A comprehensive resource by Hadley Wickham and Garrett Grolemund that covers data science using R.

- [What they forgot to teach you about R](https://rstats.wtf/): A collection of tips and best practices for R programming by Jennifer Bryan, Jim Hester, Shannon Pileggi, E. David Ajal.

- [From R User to R Programmer](https://posit-conf-2025.github.io/r-programming/): Posit conf 2024 workshop by Emma Rand and Ian Lyttle.

- [Intro to Quarto](https://posit-conf-2024.github.io/quarto-intro/): Posit conf 2024 workshop by Andrew Bray.
