%%{
	init: {
		'theme':'base', 
		'showCommitLabel': false, 
		'themeVariables': { 
			'git0':'#6cc644', 
			'git1':'#f39c12', 
			'commitLabelColor': '#325c65', 
			'commitLabelBackground':'#325c65'
		}
	}
}%%

gitGraph
    commit id: " "
    commit id: "  "
    commit id: "   "
    commit id: "    "
    branch feature
    commit id: "     "
    commit id: "      "
    commit id: "       "
    commit id: "        "
    checkout main
    merge feature tag: "PR review & merge"
    commit id: "         "
    commit id: "          "
